services:
  web:
    build: ./src/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND=http://backend:8080
  backend:
    build: ./src/backend
    ports:
      - "8080:8080"
    environment:
      - REDISHOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"